name: cafeteria
description: Cafeteria order automatization

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.1
  firebase_auth: ^0.15.5+2
  google_fonts: ^0.3.9
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/products/
  fonts:
    - family: LineIcons
      fonts:
        - asset: fonts/LineIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path: "assets/logo/cafeteria_logo.png"
