import 'package:flutter/widgets.dart';

class LineIcons {
  LineIcons._();

  static const _kFontFam = 'LineIcons';

  static const IconData star_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xf004, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xf005, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xf007, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xf013, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xf015, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xf017, fontFamily: _kFontFam);
  static const IconData alternate_list = const IconData(0xf022, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xf02e, fontFamily: _kFontFam);
  static const IconData plus_circle = const IconData(0xf055, fontFamily: _kFontFam);
  static const IconData minus_circle = const IconData(0xf056, fontFamily: _kFontFam);
  static const IconData times_circle = const IconData(0xf057, fontFamily: _kFontFam);
  static const IconData question_circle = const IconData(0xf059, fontFamily: _kFontFam);
  static const IconData shopping_cart = const IconData(0xf07a, fontFamily: _kFontFam);
  static const IconData comments = const IconData(0xf086, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xf09d, fontFamily: _kFontFam);
  static const IconData arrow_circle_left = const IconData(0xf0a8, fontFamily: _kFontFam);
  static const IconData arrow_circle_right = const IconData(0xf0a9, fontFamily: _kFontFam);
  static const IconData arrow_circle_up = const IconData(0xf0aa, fontFamily: _kFontFam);
  static const IconData arrow_circle_down = const IconData(0xf0ab, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xf0c7, fontFamily: _kFontFam);
  static const IconData money_bill = const IconData(0xf0d6, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xf0e0, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xf0f3, fontFamily: _kFontFam);
  static const IconData coffee = const IconData(0xf0f4, fontFamily: _kFontFam);
  static const IconData beer = const IconData(0xf0fc, fontFamily: _kFontFam);
  static const IconData plus_square = const IconData(0xf0fe, fontFamily: _kFontFam);
  static const IconData minus_square = const IconData(0xf146, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xf14e, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xf165, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xf186, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xf1da, fontFamily: _kFontFam);
  static const IconData binoculars = const IconData(0xf1e5, fontFamily: _kFontFam);
  static const IconData bell_slash = const IconData(0xf1f6, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xf1f8, fontFamily: _kFontFam);
  static const IconData add_to_shopping_cart = const IconData(0xf217, fontFamily: _kFontFam);
  static const IconData shopping_cart_arrow_down = const IconData(0xf218, fontFamily: _kFontFam);
  static const IconData hourglass_start = const IconData(0xf251, fontFamily: _kFontFam);
  static const IconData hourglass_half = const IconData(0xf252, fontFamily: _kFontFam);
  static const IconData hourglass_end = const IconData(0xf253, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xf254, fontFamily: _kFontFam);
  static const IconData shopping_bag = const IconData(0xf290, fontFamily: _kFontFam);
  static const IconData shopping_basket = const IconData(0xf291, fontFamily: _kFontFam);
  static const IconData envelope_open = const IconData(0xf2b6, fontFamily: _kFontFam);
  static const IconData address_book = const IconData(0xf2b9, fontFamily: _kFontFam);
  static const IconData user_circle = const IconData(0xf2bd, fontFamily: _kFontFam);
  static const IconData identification_card = const IconData(0xf2c2, fontFamily: _kFontFam);
  static const IconData utensils = const IconData(0xf2e7, fontFamily: _kFontFam);
  static const IconData alternate_trash = const IconData(0xf2ed, fontFamily: _kFontFam);
  static const IconData alternate_sign_out = const IconData(0xf2f5, fontFamily: _kFontFam);
  static const IconData alternate_sign_in = const IconData(0xf2f6, fontFamily: _kFontFam);
  static const IconData alternate_redo = const IconData(0xf2f9, fontFamily: _kFontFam);
  static const IconData alternate_exchange = const IconData(0xf362, fontFamily: _kFontFam);
  static const IconData window_close = const IconData(0xf410, fontFamily: _kFontFam);
  static const IconData comment_dots = const IconData(0xf4ad, fontFamily: _kFontFam);
  static const IconData book_open = const IconData(0xf518, fontFamily: _kFontFam);
  static const IconData wavy_money_bill = const IconData(0xf53a, fontFamily: _kFontFam);
  static const IconData money_check = const IconData(0xf53c, fontFamily: _kFontFam);
  static const IconData alternate_money_check = const IconData(0xf53d, fontFamily: _kFontFam);
  static const IconData receipt = const IconData(0xf543, fontFamily: _kFontFam);
  static const IconData fruit_apple = const IconData(0xf5d1, fontFamily: _kFontFam);
  static const IconData hamburger = const IconData(0xf805, fontFamily: _kFontFam);
  static const IconData pizza_slice = const IconData(0xf818, fontFamily: _kFontFam);
  static const IconData trash_restore = const IconData(0xf829, fontFamily: _kFontFam);
  static const IconData alternative_trash_restore = const IconData(0xf82a, fontFamily: _kFontFam);
}
